services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    networks:
      - public
    env_file:
      - ./web/.env.prod
    ports:
      - '3000:3000'
    volumes:
     - ./web:/app
     - /app/node_modules
     - /app/.next

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env.prod
    networks:
      - public
      - private
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:4242
    volumes:
      - .:/code
      - ollama-data:/root/.ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    dns:
      - 8.8.8.8
      - 8.8.4.4
    entrypoint: ["/code/script/run-ollama.sh"]
    networks:
      - public

volumes:
  ollama-data:

networks:
  public:
    driver: bridge
  private:
    driver: bridge
