apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-storage
  hostPath:
    path: '/root/.ollama'
  persistentVolumeReclaimPolicy: Retain
