name: Check-Web-Compilation

on: [workflow_call]

jobs:
  check-compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        working-directory: ./news-context-front
      - name: Build project & Linter check typing
        run: npm run build --if-present
        working-directory: ./news-context-front
